/**
 * Полный учебный список неправильных глаголов (~200).
 * Запуск из web/: npx tsx scripts/build-irregular-verbs-json.ts
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

type Freq = 'must_know' | 'high' | 'medium' | 'low'
type Diff = 'easy' | 'medium' | 'hard'

type Verb = {
  infinitive: string
  past_simple: string
  past_participle: string
  group_number: number
  frequency: Freq
  difficulty: Diff
  mnemonic_tip: string
  related_verbs: string[]
  examples: Array<{ form_type: 'base' | 'past' | 'participle'; sentence_en: string; sentence_ru: string; context: string }>
}

const rows: Array<[string, string, string, number, Freq?, Diff?]> = [
  ['be', 'was/were', 'been', 6, 'must_know', 'easy'],
  ['have', 'had', 'had', 6, 'must_know', 'easy'],
  ['do', 'did', 'done', 6, 'must_know', 'easy'],
  ['say', 'said', 'said', 4, 'must_know', 'easy'],
  ['go', 'went', 'gone', 6, 'must_know', 'easy'],
  ['get', 'got', 'got', 4, 'must_know', 'easy'],
  ['make', 'made', 'made', 4, 'must_know', 'easy'],
  ['know', 'knew', 'known', 5, 'must_know', 'easy'],
  ['think', 'thought', 'thought', 4, 'must_know', 'easy'],
  ['take', 'took', 'taken', 5, 'must_know', 'easy'],
  ['see', 'saw', 'seen', 5, 'must_know', 'easy'],
  ['come', 'came', 'come', 6, 'must_know', 'easy'],
  ['find', 'found', 'found', 4, 'must_know', 'easy'],
  ['give', 'gave', 'given', 5, 'must_know', 'easy'],
  ['tell', 'told', 'told', 4, 'must_know', 'easy'],
  ['become', 'became', 'become', 6, 'high', 'easy'],
  ['leave', 'left', 'left', 4, 'high', 'easy'],
  ['feel', 'felt', 'felt', 4, 'high', 'easy'],
  ['put', 'put', 'put', 1, 'must_know', 'easy'],
  ['bring', 'brought', 'brought', 4, 'high', 'easy'],
  ['begin', 'began', 'begun', 3, 'high', 'medium'],
  ['keep', 'kept', 'kept', 4, 'high', 'easy'],
  ['hold', 'held', 'held', 4, 'high', 'easy'],
  ['write', 'wrote', 'written', 5, 'high', 'easy'],
  ['stand', 'stood', 'stood', 4, 'high', 'easy'],
  ['hear', 'heard', 'heard', 4, 'high', 'easy'],
  ['let', 'let', 'let', 1, 'high', 'easy'],
  ['mean', 'meant', 'meant', 4, 'high', 'easy'],
  ['set', 'set', 'set', 1, 'high', 'easy'],
  ['meet', 'met', 'met', 4, 'high', 'easy'],
  ['run', 'ran', 'run', 6, 'high', 'easy'],
  ['pay', 'paid', 'paid', 4, 'high', 'easy'],
  ['sit', 'sat', 'sat', 4, 'high', 'easy'],
  ['speak', 'spoke', 'spoken', 5, 'high', 'easy'],
  ['lie', 'lay', 'lain', 5, 'medium', 'hard'],
  ['lead', 'led', 'led', 4, 'high', 'easy'],
  ['read', 'read', 'read', 1, 'must_know', 'easy'],
  ['grow', 'grew', 'grown', 5, 'high', 'medium'],
  ['lose', 'lost', 'lost', 4, 'high', 'easy'],
  ['fall', 'fell', 'fallen', 5, 'high', 'medium'],
  ['send', 'sent', 'sent', 4, 'high', 'easy'],
  ['build', 'built', 'built', 4, 'high', 'easy'],
  ['understand', 'understood', 'understood', 4, 'high', 'easy'],
  ['draw', 'drew', 'drawn', 5, 'medium', 'medium'],
  ['break', 'broke', 'broken', 5, 'high', 'easy'],
  ['spend', 'spent', 'spent', 4, 'high', 'easy'],
  ['cut', 'cut', 'cut', 1, 'must_know', 'easy'],
  ['rise', 'rose', 'risen', 5, 'medium', 'medium'],
  ['drive', 'drove', 'driven', 5, 'high', 'medium'],
  ['buy', 'bought', 'bought', 4, 'must_know', 'easy'],
  ['wear', 'wore', 'worn', 5, 'high', 'medium'],
  ['choose', 'chose', 'chosen', 5, 'high', 'easy'],
  ['seek', 'sought', 'sought', 4, 'medium', 'hard'],
  ['throw', 'threw', 'thrown', 5, 'high', 'medium'],
  ['catch', 'caught', 'caught', 4, 'high', 'easy'],
  ['deal', 'dealt', 'dealt', 4, 'medium', 'medium'],
  ['win', 'won', 'won', 4, 'high', 'easy'],
  ['forget', 'forgot', 'forgotten', 5, 'high', 'medium'],
  ['lay', 'laid', 'laid', 4, 'medium', 'hard'],
  ['sell', 'sold', 'sold', 4, 'high', 'easy'],
  ['fight', 'fought', 'fought', 4, 'medium', 'medium'],
  ['bear', 'bore', 'born', 5, 'medium', 'hard'],
  ['eat', 'ate', 'eaten', 5, 'must_know', 'easy'],
  ['teach', 'taught', 'taught', 4, 'high', 'easy'],
  ['sing', 'sang', 'sung', 3, 'high', 'easy'],
  ['strike', 'struck', 'struck', 4, 'medium', 'medium'],
  ['hang', 'hung', 'hung', 4, 'medium', 'medium'],
  ['shake', 'shook', 'shaken', 5, 'medium', 'medium'],
  ['ride', 'rode', 'ridden', 5, 'high', 'medium'],
  ['fly', 'flew', 'flown', 5, 'high', 'medium'],
  ['buy', 'bought', 'bought', 4, 'must_know', 'easy'],
  ['sleep', 'slept', 'slept', 4, 'high', 'easy'],
  ['drink', 'drank', 'drunk', 3, 'high', 'easy'],
  ['hit', 'hit', 'hit', 1, 'high', 'easy'],
  ['swim', 'swam', 'swum', 3, 'high', 'easy'],
  ['cost', 'cost', 'cost', 1, 'high', 'easy'],
  ['hurt', 'hurt', 'hurt', 1, 'high', 'easy'],
  ['shut', 'shut', 'shut', 1, 'medium', 'easy'],
  ['spread', 'spread', 'spread', 1, 'medium', 'easy'],
  ['quit', 'quit', 'quit', 1, 'medium', 'easy'],
  ['split', 'split', 'split', 1, 'medium', 'easy'],
  ['fit', 'fit', 'fit', 1, 'medium', 'easy'],
  ['bet', 'bet', 'bet', 1, 'low', 'easy'],
  ['bid', 'bid', 'bid', 1, 'low', 'medium'],
  ['burst', 'burst', 'burst', 1, 'low', 'medium'],
  ['cast', 'cast', 'cast', 1, 'low', 'medium'],
  ['cut', 'cut', 'cut', 1, 'must_know', 'easy'],
  ['let', 'let', 'let', 1, 'high', 'easy'],
  ['set', 'set', 'set', 1, 'high', 'easy'],
  ['put', 'put', 'put', 1, 'must_know', 'easy'],
  ['read', 'read', 'read', 1, 'must_know', 'easy'],
  ['become', 'became', 'become', 6, 'high', 'easy'],
  ['run', 'ran', 'run', 6, 'high', 'easy'],
  ['come', 'came', 'come', 6, 'must_know', 'easy'],
  ['begin', 'began', 'begun', 3, 'high', 'medium'],
  ['drink', 'drank', 'drunk', 3, 'high', 'easy'],
  ['ring', 'rang', 'rung', 3, 'medium', 'medium'],
  ['sing', 'sang', 'sung', 3, 'high', 'easy'],
  ['sink', 'sank', 'sunk', 3, 'medium', 'medium'],
  ['spring', 'sprang', 'sprung', 3, 'low', 'hard'],
  ['stink', 'stank', 'stunk', 3, 'low', 'hard'],
  ['swim', 'swam', 'swum', 3, 'high', 'easy'],
  ['shrink', 'shrank', 'shrunk', 3, 'low', 'hard'],
  ['blow', 'blew', 'blown', 5, 'medium', 'medium'],
  ['grow', 'grew', 'grown', 5, 'high', 'medium'],
  ['know', 'knew', 'known', 5, 'must_know', 'easy'],
  ['throw', 'threw', 'thrown', 5, 'high', 'medium'],
  ['draw', 'drew', 'drawn', 5, 'medium', 'medium'],
  ['fly', 'flew', 'flown', 5, 'high', 'medium'],
  ['show', 'showed', 'shown', 5, 'high', 'easy'],
  ['break', 'broke', 'broken', 5, 'high', 'easy'],
  ['choose', 'chose', 'chosen', 5, 'high', 'easy'],
  ['freeze', 'froze', 'frozen', 5, 'medium', 'medium'],
  ['speak', 'spoke', 'spoken', 5, 'high', 'easy'],
  ['steal', 'stole', 'stolen', 5, 'medium', 'medium'],
  ['wake', 'woke', 'woken', 5, 'high', 'easy'],
  ['weave', 'wove', 'woven', 5, 'low', 'hard'],
  ['drive', 'drove', 'driven', 5, 'high', 'medium'],
  ['ride', 'rode', 'ridden', 5, 'high', 'medium'],
  ['rise', 'rose', 'risen', 5, 'medium', 'medium'],
  ['write', 'wrote', 'written', 5, 'high', 'easy'],
  ['bite', 'bit', 'bitten', 5, 'medium', 'medium'],
  ['hide', 'hid', 'hidden', 5, 'medium', 'medium'],
  ['eat', 'ate', 'eaten', 5, 'must_know', 'easy'],
  ['fall', 'fell', 'fallen', 5, 'high', 'medium'],
  ['forget', 'forgot', 'forgotten', 5, 'high', 'medium'],
  ['forgive', 'forgave', 'forgiven', 5, 'medium', 'medium'],
  ['give', 'gave', 'given', 5, 'must_know', 'easy'],
  ['see', 'saw', 'seen', 5, 'must_know', 'easy'],
  ['take', 'took', 'taken', 5, 'must_know', 'easy'],
  ['shake', 'shook', 'shaken', 5, 'medium', 'medium'],
  ['mistake', 'mistook', 'mistaken', 5, 'medium', 'hard'],
  ['undertake', 'undertook', 'undertaken', 5, 'low', 'hard'],
  ['beat', 'beat', 'beaten', 5, 'medium', 'medium'],
  ['swear', 'swore', 'sworn', 5, 'medium', 'medium'],
  ['tear', 'tore', 'torn', 5, 'medium', 'medium'],
  ['wear', 'wore', 'worn', 5, 'high', 'medium'],
  ['bear', 'bore', 'born', 5, 'medium', 'hard'],
  ['swear', 'swore', 'sworn', 5, 'medium', 'medium'],
  ['lie', 'lay', 'lain', 5, 'medium', 'hard'],
  ['buy', 'bought', 'bought', 4, 'must_know', 'easy'],
  ['bring', 'brought', 'brought', 4, 'high', 'easy'],
  ['think', 'thought', 'thought', 4, 'must_know', 'easy'],
  ['catch', 'caught', 'caught', 4, 'high', 'easy'],
  ['teach', 'taught', 'taught', 4, 'high', 'easy'],
  ['seek', 'sought', 'sought', 4, 'medium', 'hard'],
  ['fight', 'fought', 'fought', 4, 'medium', 'medium'],
  ['feel', 'felt', 'felt', 4, 'high', 'easy'],
  ['keep', 'kept', 'kept', 4, 'high', 'easy'],
  ['leave', 'left', 'left', 4, 'high', 'easy'],
  ['sleep', 'slept', 'slept', 4, 'high', 'easy'],
  ['sweep', 'swept', 'swept', 4, 'medium', 'medium'],
  ['weep', 'wept', 'wept', 4, 'low', 'hard'],
  ['mean', 'meant', 'meant', 4, 'high', 'easy'],
  ['deal', 'dealt', 'dealt', 4, 'medium', 'medium'],
  ['dream', 'dreamt', 'dreamt', 4, 'medium', 'medium'],
  ['lean', 'leant', 'leant', 4, 'low', 'medium'],
  ['learn', 'learnt', 'learnt', 4, 'high', 'easy'],
  ['burn', 'burnt', 'burnt', 4, 'medium', 'easy'],
  ['build', 'built', 'built', 4, 'high', 'easy'],
  ['lend', 'lent', 'lent', 4, 'medium', 'easy'],
  ['send', 'sent', 'sent', 4, 'high', 'easy'],
  ['spend', 'spent', 'spent', 4, 'high', 'easy'],
  ['bend', 'bent', 'bent', 4, 'medium', 'easy'],
  ['lose', 'lost', 'lost', 4, 'high', 'easy'],
  ['shoot', 'shot', 'shot', 4, 'medium', 'easy'],
  ['sit', 'sat', 'sat', 4, 'high', 'easy'],
  ['win', 'won', 'won', 4, 'high', 'easy'],
  ['shine', 'shone', 'shone', 4, 'medium', 'medium'],
  ['stick', 'stuck', 'stuck', 4, 'medium', 'easy'],
  ['strike', 'struck', 'struck', 4, 'medium', 'medium'],
  ['swing', 'swung', 'swung', 4, 'medium', 'medium'],
  ['hang', 'hung', 'hung', 4, 'medium', 'medium'],
  ['dig', 'dug', 'dug', 4, 'medium', 'easy'],
  ['spin', 'spun', 'spun', 4, 'low', 'medium'],
  ['stand', 'stood', 'stood', 4, 'high', 'easy'],
  ['understand', 'understood', 'understood', 4, 'high', 'easy'],
  ['find', 'found', 'found', 4, 'must_know', 'easy'],
  ['bind', 'bound', 'bound', 4, 'low', 'hard'],
  ['grind', 'ground', 'ground', 4, 'low', 'hard'],
  ['wind', 'wound', 'wound', 4, 'low', 'hard'],
  ['tell', 'told', 'told', 4, 'must_know', 'easy'],
  ['sell', 'sold', 'sold', 4, 'high', 'easy'],
  ['hold', 'held', 'held', 4, 'high', 'easy'],
  ['make', 'made', 'made', 4, 'must_know', 'easy'],
  ['have', 'had', 'had', 6, 'must_know', 'easy'],
  ['hear', 'heard', 'heard', 4, 'high', 'easy'],
  ['say', 'said', 'said', 4, 'must_know', 'easy'],
  ['pay', 'paid', 'paid', 4, 'high', 'easy'],
  ['lay', 'laid', 'laid', 4, 'medium', 'hard'],
  ['lead', 'led', 'led', 4, 'high', 'easy'],
  ['feed', 'fed', 'fed', 4, 'medium', 'easy'],
  ['bleed', 'bled', 'bled', 4, 'low', 'medium'],
  ['breed', 'bred', 'bred', 4, 'low', 'hard'],
  ['speed', 'sped', 'sped', 4, 'low', 'medium'],
  ['meet', 'met', 'met', 4, 'high', 'easy'],
  ['light', 'lit', 'lit', 4, 'medium', 'easy'],
  ['slide', 'slid', 'slid', 4, 'medium', 'medium'],
  ['get', 'got', 'got', 4, 'must_know', 'easy'],
  ['forget', 'forgot', 'forgotten', 5, 'high', 'medium'],
  ['sit', 'sat', 'sat', 4, 'high', 'easy'],
  ['spit', 'spat', 'spat', 4, 'low', 'hard'],
  ['go', 'went', 'gone', 6, 'must_know', 'easy'],
  ['do', 'did', 'done', 6, 'must_know', 'easy'],
  ['be', 'was/were', 'been', 6, 'must_know', 'easy'],
  ['am', 'was', 'been', 6, 'must_know', 'easy'],
  ['is', 'was', 'been', 6, 'must_know', 'easy'],
  ['are', 'were', 'been', 6, 'must_know', 'easy'],
  ['can', 'could', 'could', 6, 'must_know', 'easy'],
  ['will', 'would', 'would', 6, 'must_know', 'easy'],
  ['shall', 'should', 'should', 6, 'medium', 'medium'],
  ['may', 'might', 'might', 6, 'high', 'easy'],
  ['must', 'had to', 'had to', 6, 'high', 'easy'],
  ['awake', 'awoke', 'awoken', 5, 'low', 'hard'],
  ['arise', 'arose', 'arisen', 5, 'low', 'hard'],
  ['broadcast', 'broadcast', 'broadcast', 1, 'medium', 'medium'],
  ['forecast', 'forecast', 'forecast', 1, 'low', 'medium'],
  ['overcome', 'overcame', 'overcome', 6, 'medium', 'medium'],
  ['overtake', 'overtook', 'overtaken', 5, 'medium', 'hard'],
  ['undergo', 'underwent', 'undergone', 6, 'medium', 'hard'],
  ['upset', 'upset', 'upset', 1, 'medium', 'easy'],
  ['rewind', 'rewound', 'rewound', 4, 'low', 'hard'],
  ['rewrite', 'rewrote', 'rewritten', 5, 'medium', 'medium'],
  ['withdraw', 'withdrew', 'withdrawn', 5, 'medium', 'hard'],
  ['withstand', 'withstood', 'withstood', 4, 'low', 'hard'],
  ['forbid', 'forbade', 'forbidden', 5, 'medium', 'hard'],
  ['forecast', 'forecast', 'forecast', 1, 'low', 'medium'],
  ['input', 'input', 'input', 1, 'medium', 'easy'],
  ['output', 'output', 'output', 1, 'low', 'easy'],
  ['offset', 'offset', 'offset', 1, 'low', 'hard'],
  ['proofread', 'proofread', 'proofread', 1, 'low', 'hard'],
  ['quit', 'quit', 'quit', 1, 'medium', 'easy'],
  ['rid', 'rid', 'rid', 1, 'low', 'medium'],
  ['shed', 'shed', 'shed', 1, 'low', 'medium'],
  ['slit', 'slit', 'slit', 1, 'low', 'hard'],
  ['thrust', 'thrust', 'thrust', 1, 'low', 'hard'],
  ['wed', 'wed', 'wed', 1, 'low', 'medium'],
  ['wet', 'wet', 'wet', 1, 'low', 'easy'],
  ['knit', 'knit', 'knit', 1, 'low', 'medium'],
  ['creep', 'crept', 'crept', 4, 'low', 'hard'],
  ['leap', 'leapt', 'leapt', 4, 'low', 'medium'],
  ['kneel', 'knelt', 'knelt', 4, 'low', 'hard'],
  ['smell', 'smelt', 'smelt', 4, 'medium', 'easy'],
  ['spell', 'spelt', 'spelt', 4, 'medium', 'easy'],
  ['spill', 'spilt', 'spilt', 4, 'medium', 'easy'],
  ['spoil', 'spoilt', 'spoilt', 4, 'medium', 'easy'],
  ['dwell', 'dwelt', 'dwelt', 4, 'low', 'hard'],
  ['cling', 'clung', 'clung', 4, 'low', 'hard'],
  ['fling', 'flung', 'flung', 4, 'low', 'hard'],
  ['sling', 'slung', 'slung', 4, 'low', 'hard'],
  ['sting', 'stung', 'stung', 4, 'medium', 'medium'],
  ['string', 'strung', 'strung', 4, 'low', 'hard'],
  ['wring', 'wrung', 'wrung', 4, 'low', 'hard'],
  ['stick', 'stuck', 'stuck', 4, 'medium', 'easy'],
  ['strike', 'struck', 'struck', 4, 'medium', 'medium'],
  ['sneak', 'snuck', 'snuck', 4, 'low', 'medium'],
  ['dive', 'dove', 'dived', 5, 'medium', 'medium'],
  ['thrive', 'throve', 'thriven', 5, 'low', 'hard'],
  ['strive', 'strove', 'striven', 5, 'low', 'hard'],
  ['weave', 'wove', 'woven', 5, 'low', 'hard'],
  ['freeze', 'froze', 'frozen', 5, 'medium', 'medium'],
  ['choose', 'chose', 'chosen', 5, 'high', 'easy'],
  ['speak', 'spoke', 'spoken', 5, 'high', 'easy'],
  ['steal', 'stole', 'stolen', 5, 'medium', 'medium'],
  ['wake', 'woke', 'woken', 5, 'high', 'easy'],
  ['break', 'broke', 'broken', 5, 'high', 'easy'],
  ['awake', 'awoke', 'awoken', 5, 'low', 'hard'],
  ['swear', 'swore', 'sworn', 5, 'medium', 'medium'],
  ['tear', 'tore', 'torn', 5, 'medium', 'medium'],
  ['wear', 'wore', 'worn', 5, 'high', 'medium'],
  ['bear', 'bore', 'born', 5, 'medium', 'hard'],
  ['shear', 'shore', 'shorn', 5, 'low', 'hard'],
  ['swear', 'swore', 'sworn', 5, 'medium', 'medium'],
  ['behold', 'beheld', 'beheld', 4, 'low', 'hard'],
  ['uphold', 'upheld', 'upheld', 4, 'low', 'hard'],
  ['withhold', 'withheld', 'withheld', 4, 'low', 'hard'],
  ['beget', 'begot', 'begotten', 5, 'low', 'hard'],
  ['forbid', 'forbade', 'forbidden', 5, 'medium', 'hard'],
  ['forgive', 'forgave', 'forgiven', 5, 'medium', 'medium'],
  ['forsake', 'forsook', 'forsaken', 5, 'low', 'hard'],
  ['mistake', 'mistook', 'mistaken', 5, 'medium', 'hard'],
  ['overtake', 'overtook', 'overtaken', 5, 'medium', 'hard'],
  ['partake', 'partook', 'partaken', 5, 'low', 'hard'],
  ['retake', 'retook', 'retaken', 5, 'low', 'hard'],
  ['shake', 'shook', 'shaken', 5, 'medium', 'medium'],
  ['take', 'took', 'taken', 5, 'must_know', 'easy'],
  ['undertake', 'undertook', 'undertaken', 5, 'low', 'hard'],
  ['arise', 'arose', 'arisen', 5, 'low', 'hard'],
  ['rise', 'rose', 'risen', 5, 'medium', 'medium'],
  ['write', 'wrote', 'written', 5, 'high', 'easy'],
  ['rewrite', 'rewrote', 'rewritten', 5, 'medium', 'medium'],
  ['smite', 'smote', 'smitten', 5, 'low', 'hard'],
]

function examples(inf: string, past: string, part: string): Verb['examples'] {
  return [
    { form_type: 'base', sentence_en: `I ${inf} every day.`, sentence_ru: `Я делаю это (${inf}) каждый день.`, context: 'Present Simple' },
    { form_type: 'past', sentence_en: `Yesterday I ${past}.`, sentence_ru: `Вчера я (${past}).`, context: 'Past Simple' },
    { form_type: 'participle', sentence_en: `I have ${part} before.`, sentence_ru: `Я уже (${part}) раньше.`, context: 'Present Perfect' },
  ]
}

const seen = new Set<string>()
const verbs: Verb[] = []
for (const [inf, past, part, group, freq = 'medium', diff = 'medium'] of rows) {
  if (seen.has(inf)) continue
  if (['am', 'is', 'are', 'can', 'will', 'shall', 'may', 'must', 'beget', 'smite'].includes(inf)) continue
  seen.add(inf)
  verbs.push({
    infinitive: inf,
    past_simple: past,
    past_participle: part,
    group_number: group,
    frequency: freq,
    difficulty: diff,
    mnemonic_tip: `${inf} — ${past} — ${part}`,
    related_verbs: [],
    examples: examples(inf, past, part),
  })
}

const out = join(process.cwd(), 'data/irregular-verbs.json')
writeFileSync(out, JSON.stringify(verbs, null, 2) + '\n')
console.log('записано глаголов:', verbs.length, out)
