/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppLevelTestRouteImport } from './routes/_app/level-test'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppVerbsRouteImport } from './routes/_app/verbs'
import { Route as AppVocabularyRouteImport } from './routes/_app/vocabulary'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as AppAiIndexRouteImport } from './routes/_app/ai/index'
import { Route as AppLessonTaskIdRouteImport } from './routes/_app/lesson.$taskId'
import { Route as ApiAiAnalyzeVoiceRouteImport } from './routes/api/ai/analyze-voice'
import { Route as ApiAiCheckWritingRouteImport } from './routes/api/ai/check-writing'
import { Route as ApiAiGenerateReadingRouteImport } from './routes/api/ai/generate-reading'
import { Route as ApiAiGrammarDrillRouteImport } from './routes/api/ai/grammar-drill'
import { Route as ApiAiPlanSummaryRouteImport } from './routes/api/ai/plan-summary'
import { Route as ApiAiSpeakingRouteImport } from './routes/api/ai/speaking'
import { Route as ApiAiTaskTextRouteImport } from './routes/api/ai/task-text'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthHasuraJwtRouteImport } from './routes/api/auth/hasura-jwt'
import { Route as ApiLessonCardsRouteImport } from './routes/api/lesson/cards'
import { Route as ApiLessonCompleteRouteImport } from './routes/api/lesson/complete'
import { Route as ApiLessonGenerateRouteImport } from './routes/api/lesson/generate'
import { Route as ApiLessonTaskRouteImport } from './routes/api/lesson/task'
import { Route as ApiLevelTestEvaluateRouteImport } from './routes/api/level-test/evaluate'
import { Route as ApiLevelTestGenerateRouteImport } from './routes/api/level-test/generate'
import { Route as ApiListeningTranscribeRouteImport } from './routes/api/listening/transcribe'
import { Route as ApiLlmHealthRouteImport } from './routes/api/llm/health'
import { Route as ApiLlmRunRouteImport } from './routes/api/llm/run'
import { Route as ApiMonitorEventsRouteImport } from './routes/api/monitor/events'
import { Route as ApiNotificationsDailyRouteImport } from './routes/api/notifications/daily'
import { Route as ApiNotificationsSubscribeRouteImport } from './routes/api/notifications/subscribe'
import { Route as ApiNotificationsTestRouteImport } from './routes/api/notifications/test'
import { Route as ApiNotificationsUnsubscribeRouteImport } from './routes/api/notifications/unsubscribe'
import { Route as ApiNotificationsVapidRouteImport } from './routes/api/notifications/vapid'
import { Route as ApiPlanGenerateRouteImport } from './routes/api/plan/generate'
import { Route as ApiPlanRequirementChecksRouteImport } from './routes/api/plan/requirement-checks'
import { Route as ApiPlanTodayRouteImport } from './routes/api/plan/today'
import { Route as ApiProgressInsightsRouteImport } from './routes/api/progress/insights'
import { Route as ApiProgressKumonRouteImport } from './routes/api/progress/kumon'
import { Route as ApiShuHaRiCheckRouteImport } from './routes/api/shu-ha-ri/check'
import { Route as ApiShuHaRiGenerateRouteImport } from './routes/api/shu-ha-ri/generate'
import { Route as ApiStageGenerateTestRouteImport } from './routes/api/stage/generate-test'
import { Route as ApiVerbsIndexRouteImport } from './routes/api/verbs/index'
import { Route as ApiVerbsVerbIdRouteImport } from './routes/api/verbs/$verbId'
import { Route as ApiVerbsAddToQueueRouteImport } from './routes/api/verbs/add-to-queue'
import { Route as ApiVerbsPracticeRouteImport } from './routes/api/verbs/practice'
import { Route as ApiVerbsPracticeSessionRouteImport } from './routes/api/verbs/practice-session'
import { Route as ApiVerbsProgressRouteImport } from './routes/api/verbs/progress'
import { Route as ApiVerbsReviewRouteImport } from './routes/api/verbs/review'
import { Route as ApiVocabularyAddWordRouteImport } from './routes/api/vocabulary/add-word'
import { Route as ApiVocabularyGenerateCardsRouteImport } from './routes/api/vocabulary/generate-cards'
import { Route as ApiVocabularyReviewRouteImport } from './routes/api/vocabulary/review'
import { Route as ApiVocabularyUpdateCardRouteImport } from './routes/api/vocabulary/update-card'
import { Route as AppAiSpeakingTaskIdRouteImport } from './routes/_app/ai/speaking.$taskId'
import { Route as AppAiVoiceTaskIdRouteImport } from './routes/_app/ai/voice.$taskId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppLevelTestRoute = AppLevelTestRouteImport.update({
  id: '/level-test',
  path: '/level-test',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVerbsRoute = AppVerbsRouteImport.update({
  id: '/verbs',
  path: '/verbs',
  getParentRoute: () => AppRoute,
} as any)
const AppVocabularyRoute = AppVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiIndexRoute = AppAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAiRoute,
} as any)
const AppLessonTaskIdRoute = AppLessonTaskIdRouteImport.update({
  id: '/lesson/$taskId',
  path: '/lesson/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAiAnalyzeVoiceRoute = ApiAiAnalyzeVoiceRouteImport.update({
  id: '/api/ai/analyze-voice',
  path: '/api/ai/analyze-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCheckWritingRoute = ApiAiCheckWritingRouteImport.update({
  id: '/api/ai/check-writing',
  path: '/api/ai/check-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateReadingRoute = ApiAiGenerateReadingRouteImport.update({
  id: '/api/ai/generate-reading',
  path: '/api/ai/generate-reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGrammarDrillRoute = ApiAiGrammarDrillRouteImport.update({
  id: '/api/ai/grammar-drill',
  path: '/api/ai/grammar-drill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPlanSummaryRoute = ApiAiPlanSummaryRouteImport.update({
  id: '/api/ai/plan-summary',
  path: '/api/ai/plan-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSpeakingRoute = ApiAiSpeakingRouteImport.update({
  id: '/api/ai/speaking',
  path: '/api/ai/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTaskTextRoute = ApiAiTaskTextRouteImport.update({
  id: '/api/ai/task-text',
  path: '/api/ai/task-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthHasuraJwtRoute = ApiAuthHasuraJwtRouteImport.update({
  id: '/api/auth/hasura-jwt',
  path: '/api/auth/hasura-jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonCardsRoute = ApiLessonCardsRouteImport.update({
  id: '/api/lesson/cards',
  path: '/api/lesson/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonCompleteRoute = ApiLessonCompleteRouteImport.update({
  id: '/api/lesson/complete',
  path: '/api/lesson/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonGenerateRoute = ApiLessonGenerateRouteImport.update({
  id: '/api/lesson/generate',
  path: '/api/lesson/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonTaskRoute = ApiLessonTaskRouteImport.update({
  id: '/api/lesson/task',
  path: '/api/lesson/task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLevelTestEvaluateRoute = ApiLevelTestEvaluateRouteImport.update({
  id: '/api/level-test/evaluate',
  path: '/api/level-test/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLevelTestGenerateRoute = ApiLevelTestGenerateRouteImport.update({
  id: '/api/level-test/generate',
  path: '/api/level-test/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListeningTranscribeRoute = ApiListeningTranscribeRouteImport.update({
  id: '/api/listening/transcribe',
  path: '/api/listening/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmHealthRoute = ApiLlmHealthRouteImport.update({
  id: '/api/llm/health',
  path: '/api/llm/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmRunRoute = ApiLlmRunRouteImport.update({
  id: '/api/llm/run',
  path: '/api/llm/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitorEventsRoute = ApiMonitorEventsRouteImport.update({
  id: '/api/monitor/events',
  path: '/api/monitor/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsDailyRoute = ApiNotificationsDailyRouteImport.update({
  id: '/api/notifications/daily',
  path: '/api/notifications/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsSubscribeRoute =
  ApiNotificationsSubscribeRouteImport.update({
    id: '/api/notifications/subscribe',
    path: '/api/notifications/subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationsTestRoute = ApiNotificationsTestRouteImport.update({
  id: '/api/notifications/test',
  path: '/api/notifications/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsUnsubscribeRoute =
  ApiNotificationsUnsubscribeRouteImport.update({
    id: '/api/notifications/unsubscribe',
    path: '/api/notifications/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationsVapidRoute = ApiNotificationsVapidRouteImport.update({
  id: '/api/notifications/vapid',
  path: '/api/notifications/vapid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanGenerateRoute = ApiPlanGenerateRouteImport.update({
  id: '/api/plan/generate',
  path: '/api/plan/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanRequirementChecksRoute =
  ApiPlanRequirementChecksRouteImport.update({
    id: '/api/plan/requirement-checks',
    path: '/api/plan/requirement-checks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlanTodayRoute = ApiPlanTodayRouteImport.update({
  id: '/api/plan/today',
  path: '/api/plan/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressInsightsRoute = ApiProgressInsightsRouteImport.update({
  id: '/api/progress/insights',
  path: '/api/progress/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressKumonRoute = ApiProgressKumonRouteImport.update({
  id: '/api/progress/kumon',
  path: '/api/progress/kumon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShuHaRiCheckRoute = ApiShuHaRiCheckRouteImport.update({
  id: '/api/shu-ha-ri/check',
  path: '/api/shu-ha-ri/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShuHaRiGenerateRoute = ApiShuHaRiGenerateRouteImport.update({
  id: '/api/shu-ha-ri/generate',
  path: '/api/shu-ha-ri/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStageGenerateTestRoute = ApiStageGenerateTestRouteImport.update({
  id: '/api/stage/generate-test',
  path: '/api/stage/generate-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsIndexRoute = ApiVerbsIndexRouteImport.update({
  id: '/api/verbs/',
  path: '/api/verbs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsVerbIdRoute = ApiVerbsVerbIdRouteImport.update({
  id: '/api/verbs/$verbId',
  path: '/api/verbs/$verbId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsAddToQueueRoute = ApiVerbsAddToQueueRouteImport.update({
  id: '/api/verbs/add-to-queue',
  path: '/api/verbs/add-to-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsPracticeRoute = ApiVerbsPracticeRouteImport.update({
  id: '/api/verbs/practice',
  path: '/api/verbs/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsPracticeSessionRoute = ApiVerbsPracticeSessionRouteImport.update({
  id: '/api/verbs/practice-session',
  path: '/api/verbs/practice-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsProgressRoute = ApiVerbsProgressRouteImport.update({
  id: '/api/verbs/progress',
  path: '/api/verbs/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsReviewRoute = ApiVerbsReviewRouteImport.update({
  id: '/api/verbs/review',
  path: '/api/verbs/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVocabularyAddWordRoute = ApiVocabularyAddWordRouteImport.update({
  id: '/api/vocabulary/add-word',
  path: '/api/vocabulary/add-word',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVocabularyGenerateCardsRoute =
  ApiVocabularyGenerateCardsRouteImport.update({
    id: '/api/vocabulary/generate-cards',
    path: '/api/vocabulary/generate-cards',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVocabularyReviewRoute = ApiVocabularyReviewRouteImport.update({
  id: '/api/vocabulary/review',
  path: '/api/vocabulary/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVocabularyUpdateCardRoute = ApiVocabularyUpdateCardRouteImport.update({
  id: '/api/vocabulary/update-card',
  path: '/api/vocabulary/update-card',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiSpeakingTaskIdRoute = AppAiSpeakingTaskIdRouteImport.update({
  id: '/speaking/$taskId',
  path: '/speaking/$taskId',
  getParentRoute: () => AppAiRoute,
} as any)
const AppAiVoiceTaskIdRoute = AppAiVoiceTaskIdRouteImport.update({
  id: '/voice/$taskId',
  path: '/voice/$taskId',
  getParentRoute: () => AppAiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/ai': typeof AppAiRouteWithChildren
  '/level-test': typeof AppLevelTestRoute
  '/progress': typeof AppProgressRoute
  '/settings': typeof AppSettingsRoute
  '/verbs': typeof AppVerbsRoute
  '/vocabulary': typeof AppVocabularyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/lesson/$taskId': typeof AppLessonTaskIdRoute
  '/api/ai/analyze-voice': typeof ApiAiAnalyzeVoiceRoute
  '/api/ai/check-writing': typeof ApiAiCheckWritingRoute
  '/api/ai/generate-reading': typeof ApiAiGenerateReadingRoute
  '/api/ai/grammar-drill': typeof ApiAiGrammarDrillRoute
  '/api/ai/plan-summary': typeof ApiAiPlanSummaryRoute
  '/api/ai/speaking': typeof ApiAiSpeakingRoute
  '/api/ai/task-text': typeof ApiAiTaskTextRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/hasura-jwt': typeof ApiAuthHasuraJwtRoute
  '/api/lesson/cards': typeof ApiLessonCardsRoute
  '/api/lesson/complete': typeof ApiLessonCompleteRoute
  '/api/lesson/generate': typeof ApiLessonGenerateRoute
  '/api/lesson/task': typeof ApiLessonTaskRoute
  '/api/level-test/evaluate': typeof ApiLevelTestEvaluateRoute
  '/api/level-test/generate': typeof ApiLevelTestGenerateRoute
  '/api/listening/transcribe': typeof ApiListeningTranscribeRoute
  '/api/llm/health': typeof ApiLlmHealthRoute
  '/api/llm/run': typeof ApiLlmRunRoute
  '/api/monitor/events': typeof ApiMonitorEventsRoute
  '/api/notifications/daily': typeof ApiNotificationsDailyRoute
  '/api/notifications/subscribe': typeof ApiNotificationsSubscribeRoute
  '/api/notifications/test': typeof ApiNotificationsTestRoute
  '/api/notifications/unsubscribe': typeof ApiNotificationsUnsubscribeRoute
  '/api/notifications/vapid': typeof ApiNotificationsVapidRoute
  '/api/plan/generate': typeof ApiPlanGenerateRoute
  '/api/plan/requirement-checks': typeof ApiPlanRequirementChecksRoute
  '/api/plan/today': typeof ApiPlanTodayRoute
  '/api/progress/insights': typeof ApiProgressInsightsRoute
  '/api/progress/kumon': typeof ApiProgressKumonRoute
  '/api/shu-ha-ri/check': typeof ApiShuHaRiCheckRoute
  '/api/shu-ha-ri/generate': typeof ApiShuHaRiGenerateRoute
  '/api/stage/generate-test': typeof ApiStageGenerateTestRoute
  '/api/verbs/$verbId': typeof ApiVerbsVerbIdRoute
  '/api/verbs/add-to-queue': typeof ApiVerbsAddToQueueRoute
  '/api/verbs/practice': typeof ApiVerbsPracticeRoute
  '/api/verbs/practice-session': typeof ApiVerbsPracticeSessionRoute
  '/api/verbs/progress': typeof ApiVerbsProgressRoute
  '/api/verbs/review': typeof ApiVerbsReviewRoute
  '/api/vocabulary/add-word': typeof ApiVocabularyAddWordRoute
  '/api/vocabulary/generate-cards': typeof ApiVocabularyGenerateCardsRoute
  '/api/vocabulary/review': typeof ApiVocabularyReviewRoute
  '/api/vocabulary/update-card': typeof ApiVocabularyUpdateCardRoute
  '/ai/': typeof AppAiIndexRoute
  '/api/verbs/': typeof ApiVerbsIndexRoute
  '/ai/speaking/$taskId': typeof AppAiSpeakingTaskIdRoute
  '/ai/voice/$taskId': typeof AppAiVoiceTaskIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/level-test': typeof AppLevelTestRoute
  '/progress': typeof AppProgressRoute
  '/settings': typeof AppSettingsRoute
  '/verbs': typeof AppVerbsRoute
  '/vocabulary': typeof AppVocabularyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/': typeof AppIndexRoute
  '/lesson/$taskId': typeof AppLessonTaskIdRoute
  '/api/ai/analyze-voice': typeof ApiAiAnalyzeVoiceRoute
  '/api/ai/check-writing': typeof ApiAiCheckWritingRoute
  '/api/ai/generate-reading': typeof ApiAiGenerateReadingRoute
  '/api/ai/grammar-drill': typeof ApiAiGrammarDrillRoute
  '/api/ai/plan-summary': typeof ApiAiPlanSummaryRoute
  '/api/ai/speaking': typeof ApiAiSpeakingRoute
  '/api/ai/task-text': typeof ApiAiTaskTextRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/hasura-jwt': typeof ApiAuthHasuraJwtRoute
  '/api/lesson/cards': typeof ApiLessonCardsRoute
  '/api/lesson/complete': typeof ApiLessonCompleteRoute
  '/api/lesson/generate': typeof ApiLessonGenerateRoute
  '/api/lesson/task': typeof ApiLessonTaskRoute
  '/api/level-test/evaluate': typeof ApiLevelTestEvaluateRoute
  '/api/level-test/generate': typeof ApiLevelTestGenerateRoute
  '/api/listening/transcribe': typeof ApiListeningTranscribeRoute
  '/api/llm/health': typeof ApiLlmHealthRoute
  '/api/llm/run': typeof ApiLlmRunRoute
  '/api/monitor/events': typeof ApiMonitorEventsRoute
  '/api/notifications/daily': typeof ApiNotificationsDailyRoute
  '/api/notifications/subscribe': typeof ApiNotificationsSubscribeRoute
  '/api/notifications/test': typeof ApiNotificationsTestRoute
  '/api/notifications/unsubscribe': typeof ApiNotificationsUnsubscribeRoute
  '/api/notifications/vapid': typeof ApiNotificationsVapidRoute
  '/api/plan/generate': typeof ApiPlanGenerateRoute
  '/api/plan/requirement-checks': typeof ApiPlanRequirementChecksRoute
  '/api/plan/today': typeof ApiPlanTodayRoute
  '/api/progress/insights': typeof ApiProgressInsightsRoute
  '/api/progress/kumon': typeof ApiProgressKumonRoute
  '/api/shu-ha-ri/check': typeof ApiShuHaRiCheckRoute
  '/api/shu-ha-ri/generate': typeof ApiShuHaRiGenerateRoute
  '/api/stage/generate-test': typeof ApiStageGenerateTestRoute
  '/api/verbs/$verbId': typeof ApiVerbsVerbIdRoute
  '/api/verbs/add-to-queue': typeof ApiVerbsAddToQueueRoute
  '/api/verbs/practice': typeof ApiVerbsPracticeRoute
  '/api/verbs/practice-session': typeof ApiVerbsPracticeSessionRoute
  '/api/verbs/progress': typeof ApiVerbsProgressRoute
  '/api/verbs/review': typeof ApiVerbsReviewRoute
  '/api/vocabulary/add-word': typeof ApiVocabularyAddWordRoute
  '/api/vocabulary/generate-cards': typeof ApiVocabularyGenerateCardsRoute
  '/api/vocabulary/review': typeof ApiVocabularyReviewRoute
  '/api/vocabulary/update-card': typeof ApiVocabularyUpdateCardRoute
  '/ai': typeof AppAiIndexRoute
  '/api/verbs': typeof ApiVerbsIndexRoute
  '/ai/speaking/$taskId': typeof AppAiSpeakingTaskIdRoute
  '/ai/voice/$taskId': typeof AppAiVoiceTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai': typeof AppAiRouteWithChildren
  '/_app/level-test': typeof AppLevelTestRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/verbs': typeof AppVerbsRoute
  '/_app/vocabulary': typeof AppVocabularyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/_app/': typeof AppIndexRoute
  '/_app/lesson/$taskId': typeof AppLessonTaskIdRoute
  '/api/ai/analyze-voice': typeof ApiAiAnalyzeVoiceRoute
  '/api/ai/check-writing': typeof ApiAiCheckWritingRoute
  '/api/ai/generate-reading': typeof ApiAiGenerateReadingRoute
  '/api/ai/grammar-drill': typeof ApiAiGrammarDrillRoute
  '/api/ai/plan-summary': typeof ApiAiPlanSummaryRoute
  '/api/ai/speaking': typeof ApiAiSpeakingRoute
  '/api/ai/task-text': typeof ApiAiTaskTextRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/hasura-jwt': typeof ApiAuthHasuraJwtRoute
  '/api/lesson/cards': typeof ApiLessonCardsRoute
  '/api/lesson/complete': typeof ApiLessonCompleteRoute
  '/api/lesson/generate': typeof ApiLessonGenerateRoute
  '/api/lesson/task': typeof ApiLessonTaskRoute
  '/api/level-test/evaluate': typeof ApiLevelTestEvaluateRoute
  '/api/level-test/generate': typeof ApiLevelTestGenerateRoute
  '/api/listening/transcribe': typeof ApiListeningTranscribeRoute
  '/api/llm/health': typeof ApiLlmHealthRoute
  '/api/llm/run': typeof ApiLlmRunRoute
  '/api/monitor/events': typeof ApiMonitorEventsRoute
  '/api/notifications/daily': typeof ApiNotificationsDailyRoute
  '/api/notifications/subscribe': typeof ApiNotificationsSubscribeRoute
  '/api/notifications/test': typeof ApiNotificationsTestRoute
  '/api/notifications/unsubscribe': typeof ApiNotificationsUnsubscribeRoute
  '/api/notifications/vapid': typeof ApiNotificationsVapidRoute
  '/api/plan/generate': typeof ApiPlanGenerateRoute
  '/api/plan/requirement-checks': typeof ApiPlanRequirementChecksRoute
  '/api/plan/today': typeof ApiPlanTodayRoute
  '/api/progress/insights': typeof ApiProgressInsightsRoute
  '/api/progress/kumon': typeof ApiProgressKumonRoute
  '/api/shu-ha-ri/check': typeof ApiShuHaRiCheckRoute
  '/api/shu-ha-ri/generate': typeof ApiShuHaRiGenerateRoute
  '/api/stage/generate-test': typeof ApiStageGenerateTestRoute
  '/api/verbs/$verbId': typeof ApiVerbsVerbIdRoute
  '/api/verbs/add-to-queue': typeof ApiVerbsAddToQueueRoute
  '/api/verbs/practice': typeof ApiVerbsPracticeRoute
  '/api/verbs/practice-session': typeof ApiVerbsPracticeSessionRoute
  '/api/verbs/progress': typeof ApiVerbsProgressRoute
  '/api/verbs/review': typeof ApiVerbsReviewRoute
  '/api/vocabulary/add-word': typeof ApiVocabularyAddWordRoute
  '/api/vocabulary/generate-cards': typeof ApiVocabularyGenerateCardsRoute
  '/api/vocabulary/review': typeof ApiVocabularyReviewRoute
  '/api/vocabulary/update-card': typeof ApiVocabularyUpdateCardRoute
  '/_app/ai/': typeof AppAiIndexRoute
  '/api/verbs/': typeof ApiVerbsIndexRoute
  '/_app/ai/speaking/$taskId': typeof AppAiSpeakingTaskIdRoute
  '/_app/ai/voice/$taskId': typeof AppAiVoiceTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai'
    | '/level-test'
    | '/progress'
    | '/settings'
    | '/verbs'
    | '/vocabulary'
    | '/api/health'
    | '/api/version'
    | '/lesson/$taskId'
    | '/api/ai/analyze-voice'
    | '/api/ai/check-writing'
    | '/api/ai/generate-reading'
    | '/api/ai/grammar-drill'
    | '/api/ai/plan-summary'
    | '/api/ai/speaking'
    | '/api/ai/task-text'
    | '/api/auth/$'
    | '/api/auth/hasura-jwt'
    | '/api/lesson/cards'
    | '/api/lesson/complete'
    | '/api/lesson/generate'
    | '/api/lesson/task'
    | '/api/level-test/evaluate'
    | '/api/level-test/generate'
    | '/api/listening/transcribe'
    | '/api/llm/health'
    | '/api/llm/run'
    | '/api/monitor/events'
    | '/api/notifications/daily'
    | '/api/notifications/subscribe'
    | '/api/notifications/test'
    | '/api/notifications/unsubscribe'
    | '/api/notifications/vapid'
    | '/api/plan/generate'
    | '/api/plan/requirement-checks'
    | '/api/plan/today'
    | '/api/progress/insights'
    | '/api/progress/kumon'
    | '/api/shu-ha-ri/check'
    | '/api/shu-ha-ri/generate'
    | '/api/stage/generate-test'
    | '/api/verbs/$verbId'
    | '/api/verbs/add-to-queue'
    | '/api/verbs/practice'
    | '/api/verbs/practice-session'
    | '/api/verbs/progress'
    | '/api/verbs/review'
    | '/api/vocabulary/add-word'
    | '/api/vocabulary/generate-cards'
    | '/api/vocabulary/review'
    | '/api/vocabulary/update-card'
    | '/ai/'
    | '/api/verbs/'
    | '/ai/speaking/$taskId'
    | '/ai/voice/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/level-test'
    | '/progress'
    | '/settings'
    | '/verbs'
    | '/vocabulary'
    | '/api/health'
    | '/api/version'
    | '/'
    | '/lesson/$taskId'
    | '/api/ai/analyze-voice'
    | '/api/ai/check-writing'
    | '/api/ai/generate-reading'
    | '/api/ai/grammar-drill'
    | '/api/ai/plan-summary'
    | '/api/ai/speaking'
    | '/api/ai/task-text'
    | '/api/auth/$'
    | '/api/auth/hasura-jwt'
    | '/api/lesson/cards'
    | '/api/lesson/complete'
    | '/api/lesson/generate'
    | '/api/lesson/task'
    | '/api/level-test/evaluate'
    | '/api/level-test/generate'
    | '/api/listening/transcribe'
    | '/api/llm/health'
    | '/api/llm/run'
    | '/api/monitor/events'
    | '/api/notifications/daily'
    | '/api/notifications/subscribe'
    | '/api/notifications/test'
    | '/api/notifications/unsubscribe'
    | '/api/notifications/vapid'
    | '/api/plan/generate'
    | '/api/plan/requirement-checks'
    | '/api/plan/today'
    | '/api/progress/insights'
    | '/api/progress/kumon'
    | '/api/shu-ha-ri/check'
    | '/api/shu-ha-ri/generate'
    | '/api/stage/generate-test'
    | '/api/verbs/$verbId'
    | '/api/verbs/add-to-queue'
    | '/api/verbs/practice'
    | '/api/verbs/practice-session'
    | '/api/verbs/progress'
    | '/api/verbs/review'
    | '/api/vocabulary/add-word'
    | '/api/vocabulary/generate-cards'
    | '/api/vocabulary/review'
    | '/api/vocabulary/update-card'
    | '/ai'
    | '/api/verbs'
    | '/ai/speaking/$taskId'
    | '/ai/voice/$taskId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/ai'
    | '/_app/level-test'
    | '/_app/progress'
    | '/_app/settings'
    | '/_app/verbs'
    | '/_app/vocabulary'
    | '/api/health'
    | '/api/version'
    | '/_app/'
    | '/_app/lesson/$taskId'
    | '/api/ai/analyze-voice'
    | '/api/ai/check-writing'
    | '/api/ai/generate-reading'
    | '/api/ai/grammar-drill'
    | '/api/ai/plan-summary'
    | '/api/ai/speaking'
    | '/api/ai/task-text'
    | '/api/auth/$'
    | '/api/auth/hasura-jwt'
    | '/api/lesson/cards'
    | '/api/lesson/complete'
    | '/api/lesson/generate'
    | '/api/lesson/task'
    | '/api/level-test/evaluate'
    | '/api/level-test/generate'
    | '/api/listening/transcribe'
    | '/api/llm/health'
    | '/api/llm/run'
    | '/api/monitor/events'
    | '/api/notifications/daily'
    | '/api/notifications/subscribe'
    | '/api/notifications/test'
    | '/api/notifications/unsubscribe'
    | '/api/notifications/vapid'
    | '/api/plan/generate'
    | '/api/plan/requirement-checks'
    | '/api/plan/today'
    | '/api/progress/insights'
    | '/api/progress/kumon'
    | '/api/shu-ha-ri/check'
    | '/api/shu-ha-ri/generate'
    | '/api/stage/generate-test'
    | '/api/verbs/$verbId'
    | '/api/verbs/add-to-queue'
    | '/api/verbs/practice'
    | '/api/verbs/practice-session'
    | '/api/verbs/progress'
    | '/api/verbs/review'
    | '/api/vocabulary/add-word'
    | '/api/vocabulary/generate-cards'
    | '/api/vocabulary/review'
    | '/api/vocabulary/update-card'
    | '/_app/ai/'
    | '/api/verbs/'
    | '/_app/ai/speaking/$taskId'
    | '/_app/ai/voice/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiAiAnalyzeVoiceRoute: typeof ApiAiAnalyzeVoiceRoute
  ApiAiCheckWritingRoute: typeof ApiAiCheckWritingRoute
  ApiAiGenerateReadingRoute: typeof ApiAiGenerateReadingRoute
  ApiAiGrammarDrillRoute: typeof ApiAiGrammarDrillRoute
  ApiAiPlanSummaryRoute: typeof ApiAiPlanSummaryRoute
  ApiAiSpeakingRoute: typeof ApiAiSpeakingRoute
  ApiAiTaskTextRoute: typeof ApiAiTaskTextRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthHasuraJwtRoute: typeof ApiAuthHasuraJwtRoute
  ApiLessonCardsRoute: typeof ApiLessonCardsRoute
  ApiLessonCompleteRoute: typeof ApiLessonCompleteRoute
  ApiLessonGenerateRoute: typeof ApiLessonGenerateRoute
  ApiLessonTaskRoute: typeof ApiLessonTaskRoute
  ApiLevelTestEvaluateRoute: typeof ApiLevelTestEvaluateRoute
  ApiLevelTestGenerateRoute: typeof ApiLevelTestGenerateRoute
  ApiListeningTranscribeRoute: typeof ApiListeningTranscribeRoute
  ApiLlmHealthRoute: typeof ApiLlmHealthRoute
  ApiLlmRunRoute: typeof ApiLlmRunRoute
  ApiMonitorEventsRoute: typeof ApiMonitorEventsRoute
  ApiNotificationsDailyRoute: typeof ApiNotificationsDailyRoute
  ApiNotificationsSubscribeRoute: typeof ApiNotificationsSubscribeRoute
  ApiNotificationsTestRoute: typeof ApiNotificationsTestRoute
  ApiNotificationsUnsubscribeRoute: typeof ApiNotificationsUnsubscribeRoute
  ApiNotificationsVapidRoute: typeof ApiNotificationsVapidRoute
  ApiPlanGenerateRoute: typeof ApiPlanGenerateRoute
  ApiPlanRequirementChecksRoute: typeof ApiPlanRequirementChecksRoute
  ApiPlanTodayRoute: typeof ApiPlanTodayRoute
  ApiProgressInsightsRoute: typeof ApiProgressInsightsRoute
  ApiProgressKumonRoute: typeof ApiProgressKumonRoute
  ApiShuHaRiCheckRoute: typeof ApiShuHaRiCheckRoute
  ApiShuHaRiGenerateRoute: typeof ApiShuHaRiGenerateRoute
  ApiStageGenerateTestRoute: typeof ApiStageGenerateTestRoute
  ApiVerbsVerbIdRoute: typeof ApiVerbsVerbIdRoute
  ApiVerbsAddToQueueRoute: typeof ApiVerbsAddToQueueRoute
  ApiVerbsPracticeRoute: typeof ApiVerbsPracticeRoute
  ApiVerbsPracticeSessionRoute: typeof ApiVerbsPracticeSessionRoute
  ApiVerbsProgressRoute: typeof ApiVerbsProgressRoute
  ApiVerbsReviewRoute: typeof ApiVerbsReviewRoute
  ApiVocabularyAddWordRoute: typeof ApiVocabularyAddWordRoute
  ApiVocabularyGenerateCardsRoute: typeof ApiVocabularyGenerateCardsRoute
  ApiVocabularyReviewRoute: typeof ApiVocabularyReviewRoute
  ApiVocabularyUpdateCardRoute: typeof ApiVocabularyUpdateCardRoute
  ApiVerbsIndexRoute: typeof ApiVerbsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/level-test': {
      id: '/_app/level-test'
      path: '/level-test'
      fullPath: '/level-test'
      preLoaderRoute: typeof AppLevelTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verbs': {
      id: '/_app/verbs'
      path: '/verbs'
      fullPath: '/verbs'
      preLoaderRoute: typeof AppVerbsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vocabulary': {
      id: '/_app/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AppVocabularyRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai/': {
      id: '/_app/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AppAiIndexRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/lesson/$taskId': {
      id: '/_app/lesson/$taskId'
      path: '/lesson/$taskId'
      fullPath: '/lesson/$taskId'
      preLoaderRoute: typeof AppLessonTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ai/analyze-voice': {
      id: '/api/ai/analyze-voice'
      path: '/api/ai/analyze-voice'
      fullPath: '/api/ai/analyze-voice'
      preLoaderRoute: typeof ApiAiAnalyzeVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/check-writing': {
      id: '/api/ai/check-writing'
      path: '/api/ai/check-writing'
      fullPath: '/api/ai/check-writing'
      preLoaderRoute: typeof ApiAiCheckWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-reading': {
      id: '/api/ai/generate-reading'
      path: '/api/ai/generate-reading'
      fullPath: '/api/ai/generate-reading'
      preLoaderRoute: typeof ApiAiGenerateReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/grammar-drill': {
      id: '/api/ai/grammar-drill'
      path: '/api/ai/grammar-drill'
      fullPath: '/api/ai/grammar-drill'
      preLoaderRoute: typeof ApiAiGrammarDrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/plan-summary': {
      id: '/api/ai/plan-summary'
      path: '/api/ai/plan-summary'
      fullPath: '/api/ai/plan-summary'
      preLoaderRoute: typeof ApiAiPlanSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/speaking': {
      id: '/api/ai/speaking'
      path: '/api/ai/speaking'
      fullPath: '/api/ai/speaking'
      preLoaderRoute: typeof ApiAiSpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/task-text': {
      id: '/api/ai/task-text'
      path: '/api/ai/task-text'
      fullPath: '/api/ai/task-text'
      preLoaderRoute: typeof ApiAiTaskTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/hasura-jwt': {
      id: '/api/auth/hasura-jwt'
      path: '/api/auth/hasura-jwt'
      fullPath: '/api/auth/hasura-jwt'
      preLoaderRoute: typeof ApiAuthHasuraJwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson/cards': {
      id: '/api/lesson/cards'
      path: '/api/lesson/cards'
      fullPath: '/api/lesson/cards'
      preLoaderRoute: typeof ApiLessonCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson/complete': {
      id: '/api/lesson/complete'
      path: '/api/lesson/complete'
      fullPath: '/api/lesson/complete'
      preLoaderRoute: typeof ApiLessonCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson/generate': {
      id: '/api/lesson/generate'
      path: '/api/lesson/generate'
      fullPath: '/api/lesson/generate'
      preLoaderRoute: typeof ApiLessonGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson/task': {
      id: '/api/lesson/task'
      path: '/api/lesson/task'
      fullPath: '/api/lesson/task'
      preLoaderRoute: typeof ApiLessonTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/level-test/evaluate': {
      id: '/api/level-test/evaluate'
      path: '/api/level-test/evaluate'
      fullPath: '/api/level-test/evaluate'
      preLoaderRoute: typeof ApiLevelTestEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/level-test/generate': {
      id: '/api/level-test/generate'
      path: '/api/level-test/generate'
      fullPath: '/api/level-test/generate'
      preLoaderRoute: typeof ApiLevelTestGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listening/transcribe': {
      id: '/api/listening/transcribe'
      path: '/api/listening/transcribe'
      fullPath: '/api/listening/transcribe'
      preLoaderRoute: typeof ApiListeningTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm/health': {
      id: '/api/llm/health'
      path: '/api/llm/health'
      fullPath: '/api/llm/health'
      preLoaderRoute: typeof ApiLlmHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm/run': {
      id: '/api/llm/run'
      path: '/api/llm/run'
      fullPath: '/api/llm/run'
      preLoaderRoute: typeof ApiLlmRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitor/events': {
      id: '/api/monitor/events'
      path: '/api/monitor/events'
      fullPath: '/api/monitor/events'
      preLoaderRoute: typeof ApiMonitorEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/daily': {
      id: '/api/notifications/daily'
      path: '/api/notifications/daily'
      fullPath: '/api/notifications/daily'
      preLoaderRoute: typeof ApiNotificationsDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/subscribe': {
      id: '/api/notifications/subscribe'
      path: '/api/notifications/subscribe'
      fullPath: '/api/notifications/subscribe'
      preLoaderRoute: typeof ApiNotificationsSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/test': {
      id: '/api/notifications/test'
      path: '/api/notifications/test'
      fullPath: '/api/notifications/test'
      preLoaderRoute: typeof ApiNotificationsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/unsubscribe': {
      id: '/api/notifications/unsubscribe'
      path: '/api/notifications/unsubscribe'
      fullPath: '/api/notifications/unsubscribe'
      preLoaderRoute: typeof ApiNotificationsUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/vapid': {
      id: '/api/notifications/vapid'
      path: '/api/notifications/vapid'
      fullPath: '/api/notifications/vapid'
      preLoaderRoute: typeof ApiNotificationsVapidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan/generate': {
      id: '/api/plan/generate'
      path: '/api/plan/generate'
      fullPath: '/api/plan/generate'
      preLoaderRoute: typeof ApiPlanGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan/requirement-checks': {
      id: '/api/plan/requirement-checks'
      path: '/api/plan/requirement-checks'
      fullPath: '/api/plan/requirement-checks'
      preLoaderRoute: typeof ApiPlanRequirementChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan/today': {
      id: '/api/plan/today'
      path: '/api/plan/today'
      fullPath: '/api/plan/today'
      preLoaderRoute: typeof ApiPlanTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress/insights': {
      id: '/api/progress/insights'
      path: '/api/progress/insights'
      fullPath: '/api/progress/insights'
      preLoaderRoute: typeof ApiProgressInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress/kumon': {
      id: '/api/progress/kumon'
      path: '/api/progress/kumon'
      fullPath: '/api/progress/kumon'
      preLoaderRoute: typeof ApiProgressKumonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shu-ha-ri/check': {
      id: '/api/shu-ha-ri/check'
      path: '/api/shu-ha-ri/check'
      fullPath: '/api/shu-ha-ri/check'
      preLoaderRoute: typeof ApiShuHaRiCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shu-ha-ri/generate': {
      id: '/api/shu-ha-ri/generate'
      path: '/api/shu-ha-ri/generate'
      fullPath: '/api/shu-ha-ri/generate'
      preLoaderRoute: typeof ApiShuHaRiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stage/generate-test': {
      id: '/api/stage/generate-test'
      path: '/api/stage/generate-test'
      fullPath: '/api/stage/generate-test'
      preLoaderRoute: typeof ApiStageGenerateTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/': {
      id: '/api/verbs/'
      path: '/api/verbs'
      fullPath: '/api/verbs/'
      preLoaderRoute: typeof ApiVerbsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/$verbId': {
      id: '/api/verbs/$verbId'
      path: '/api/verbs/$verbId'
      fullPath: '/api/verbs/$verbId'
      preLoaderRoute: typeof ApiVerbsVerbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/add-to-queue': {
      id: '/api/verbs/add-to-queue'
      path: '/api/verbs/add-to-queue'
      fullPath: '/api/verbs/add-to-queue'
      preLoaderRoute: typeof ApiVerbsAddToQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/practice': {
      id: '/api/verbs/practice'
      path: '/api/verbs/practice'
      fullPath: '/api/verbs/practice'
      preLoaderRoute: typeof ApiVerbsPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/practice-session': {
      id: '/api/verbs/practice-session'
      path: '/api/verbs/practice-session'
      fullPath: '/api/verbs/practice-session'
      preLoaderRoute: typeof ApiVerbsPracticeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/progress': {
      id: '/api/verbs/progress'
      path: '/api/verbs/progress'
      fullPath: '/api/verbs/progress'
      preLoaderRoute: typeof ApiVerbsProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/review': {
      id: '/api/verbs/review'
      path: '/api/verbs/review'
      fullPath: '/api/verbs/review'
      preLoaderRoute: typeof ApiVerbsReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vocabulary/add-word': {
      id: '/api/vocabulary/add-word'
      path: '/api/vocabulary/add-word'
      fullPath: '/api/vocabulary/add-word'
      preLoaderRoute: typeof ApiVocabularyAddWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vocabulary/generate-cards': {
      id: '/api/vocabulary/generate-cards'
      path: '/api/vocabulary/generate-cards'
      fullPath: '/api/vocabulary/generate-cards'
      preLoaderRoute: typeof ApiVocabularyGenerateCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vocabulary/review': {
      id: '/api/vocabulary/review'
      path: '/api/vocabulary/review'
      fullPath: '/api/vocabulary/review'
      preLoaderRoute: typeof ApiVocabularyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vocabulary/update-card': {
      id: '/api/vocabulary/update-card'
      path: '/api/vocabulary/update-card'
      fullPath: '/api/vocabulary/update-card'
      preLoaderRoute: typeof ApiVocabularyUpdateCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai/speaking/$taskId': {
      id: '/_app/ai/speaking/$taskId'
      path: '/speaking/$taskId'
      fullPath: '/ai/speaking/$taskId'
      preLoaderRoute: typeof AppAiSpeakingTaskIdRouteImport
      parentRoute: typeof AppAiRoute
    }
    '/_app/ai/voice/$taskId': {
      id: '/_app/ai/voice/$taskId'
      path: '/voice/$taskId'
      fullPath: '/ai/voice/$taskId'
      preLoaderRoute: typeof AppAiVoiceTaskIdRouteImport
      parentRoute: typeof AppAiRoute
    }
  }
}

interface AppAiRouteChildren {
  AppAiIndexRoute: typeof AppAiIndexRoute
  AppAiSpeakingTaskIdRoute: typeof AppAiSpeakingTaskIdRoute
  AppAiVoiceTaskIdRoute: typeof AppAiVoiceTaskIdRoute
}

const AppAiRouteChildren: AppAiRouteChildren = {
  AppAiIndexRoute: AppAiIndexRoute,
  AppAiSpeakingTaskIdRoute: AppAiSpeakingTaskIdRoute,
  AppAiVoiceTaskIdRoute: AppAiVoiceTaskIdRoute,
}

const AppAiRouteWithChildren = AppAiRoute._addFileChildren(AppAiRouteChildren)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRouteWithChildren
  AppLevelTestRoute: typeof AppLevelTestRoute
  AppProgressRoute: typeof AppProgressRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVerbsRoute: typeof AppVerbsRoute
  AppVocabularyRoute: typeof AppVocabularyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLessonTaskIdRoute: typeof AppLessonTaskIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRouteWithChildren,
  AppLevelTestRoute: AppLevelTestRoute,
  AppProgressRoute: AppProgressRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVerbsRoute: AppVerbsRoute,
  AppVocabularyRoute: AppVocabularyRoute,
  AppIndexRoute: AppIndexRoute,
  AppLessonTaskIdRoute: AppLessonTaskIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiAiAnalyzeVoiceRoute: ApiAiAnalyzeVoiceRoute,
  ApiAiCheckWritingRoute: ApiAiCheckWritingRoute,
  ApiAiGenerateReadingRoute: ApiAiGenerateReadingRoute,
  ApiAiGrammarDrillRoute: ApiAiGrammarDrillRoute,
  ApiAiPlanSummaryRoute: ApiAiPlanSummaryRoute,
  ApiAiSpeakingRoute: ApiAiSpeakingRoute,
  ApiAiTaskTextRoute: ApiAiTaskTextRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthHasuraJwtRoute: ApiAuthHasuraJwtRoute,
  ApiLessonCardsRoute: ApiLessonCardsRoute,
  ApiLessonCompleteRoute: ApiLessonCompleteRoute,
  ApiLessonGenerateRoute: ApiLessonGenerateRoute,
  ApiLessonTaskRoute: ApiLessonTaskRoute,
  ApiLevelTestEvaluateRoute: ApiLevelTestEvaluateRoute,
  ApiLevelTestGenerateRoute: ApiLevelTestGenerateRoute,
  ApiListeningTranscribeRoute: ApiListeningTranscribeRoute,
  ApiLlmHealthRoute: ApiLlmHealthRoute,
  ApiLlmRunRoute: ApiLlmRunRoute,
  ApiMonitorEventsRoute: ApiMonitorEventsRoute,
  ApiNotificationsDailyRoute: ApiNotificationsDailyRoute,
  ApiNotificationsSubscribeRoute: ApiNotificationsSubscribeRoute,
  ApiNotificationsTestRoute: ApiNotificationsTestRoute,
  ApiNotificationsUnsubscribeRoute: ApiNotificationsUnsubscribeRoute,
  ApiNotificationsVapidRoute: ApiNotificationsVapidRoute,
  ApiPlanGenerateRoute: ApiPlanGenerateRoute,
  ApiPlanRequirementChecksRoute: ApiPlanRequirementChecksRoute,
  ApiPlanTodayRoute: ApiPlanTodayRoute,
  ApiProgressInsightsRoute: ApiProgressInsightsRoute,
  ApiProgressKumonRoute: ApiProgressKumonRoute,
  ApiShuHaRiCheckRoute: ApiShuHaRiCheckRoute,
  ApiShuHaRiGenerateRoute: ApiShuHaRiGenerateRoute,
  ApiStageGenerateTestRoute: ApiStageGenerateTestRoute,
  ApiVerbsVerbIdRoute: ApiVerbsVerbIdRoute,
  ApiVerbsAddToQueueRoute: ApiVerbsAddToQueueRoute,
  ApiVerbsPracticeRoute: ApiVerbsPracticeRoute,
  ApiVerbsPracticeSessionRoute: ApiVerbsPracticeSessionRoute,
  ApiVerbsProgressRoute: ApiVerbsProgressRoute,
  ApiVerbsReviewRoute: ApiVerbsReviewRoute,
  ApiVocabularyAddWordRoute: ApiVocabularyAddWordRoute,
  ApiVocabularyGenerateCardsRoute: ApiVocabularyGenerateCardsRoute,
  ApiVocabularyReviewRoute: ApiVocabularyReviewRoute,
  ApiVocabularyUpdateCardRoute: ApiVocabularyUpdateCardRoute,
  ApiVerbsIndexRoute: ApiVerbsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
