/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthHasuraJwtRouteImport } from './routes/api/auth/hasura-jwt'
import { Route as ApiVerbsIndexRouteImport } from './routes/api/verbs/index'
import { Route as ApiVerbsVerbIdRouteImport } from './routes/api/verbs/$verbId'
import { Route as ApiVerbsAddToQueueRouteImport } from './routes/api/verbs/add-to-queue'
import { Route as ApiVerbsPracticeRouteImport } from './routes/api/verbs/practice'
import { Route as ApiVerbsPracticeSessionRouteImport } from './routes/api/verbs/practice-session'
import { Route as ApiVerbsProgressRouteImport } from './routes/api/verbs/progress'
import { Route as ApiVerbsReviewRouteImport } from './routes/api/verbs/review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthHasuraJwtRoute = ApiAuthHasuraJwtRouteImport.update({
  id: '/api/auth/hasura-jwt',
  path: '/api/auth/hasura-jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsIndexRoute = ApiVerbsIndexRouteImport.update({
  id: '/api/verbs/',
  path: '/api/verbs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsVerbIdRoute = ApiVerbsVerbIdRouteImport.update({
  id: '/api/verbs/$verbId',
  path: '/api/verbs/$verbId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsAddToQueueRoute = ApiVerbsAddToQueueRouteImport.update({
  id: '/api/verbs/add-to-queue',
  path: '/api/verbs/add-to-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsPracticeRoute = ApiVerbsPracticeRouteImport.update({
  id: '/api/verbs/practice',
  path: '/api/verbs/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsPracticeSessionRoute = ApiVerbsPracticeSessionRouteImport.update({
  id: '/api/verbs/practice-session',
  path: '/api/verbs/practice-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsProgressRoute = ApiVerbsProgressRouteImport.update({
  id: '/api/verbs/progress',
  path: '/api/verbs/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerbsReviewRoute = ApiVerbsReviewRouteImport.update({
  id: '/api/verbs/review',
  path: '/api/verbs/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/hasura-jwt': typeof ApiAuthHasuraJwtRoute
  '/api/verbs/$verbId': typeof ApiVerbsVerbIdRoute
  '/api/verbs/add-to-queue': typeof ApiVerbsAddToQueueRoute
  '/api/verbs/practice': typeof ApiVerbsPracticeRoute
  '/api/verbs/practice-session': typeof ApiVerbsPracticeSessionRoute
  '/api/verbs/progress': typeof ApiVerbsProgressRoute
  '/api/verbs/review': typeof ApiVerbsReviewRoute
  '/api/verbs/': typeof ApiVerbsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/hasura-jwt': typeof ApiAuthHasuraJwtRoute
  '/api/verbs/$verbId': typeof ApiVerbsVerbIdRoute
  '/api/verbs/add-to-queue': typeof ApiVerbsAddToQueueRoute
  '/api/verbs/practice': typeof ApiVerbsPracticeRoute
  '/api/verbs/practice-session': typeof ApiVerbsPracticeSessionRoute
  '/api/verbs/progress': typeof ApiVerbsProgressRoute
  '/api/verbs/review': typeof ApiVerbsReviewRoute
  '/api/verbs': typeof ApiVerbsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/hasura-jwt': typeof ApiAuthHasuraJwtRoute
  '/api/verbs/$verbId': typeof ApiVerbsVerbIdRoute
  '/api/verbs/add-to-queue': typeof ApiVerbsAddToQueueRoute
  '/api/verbs/practice': typeof ApiVerbsPracticeRoute
  '/api/verbs/practice-session': typeof ApiVerbsPracticeSessionRoute
  '/api/verbs/progress': typeof ApiVerbsProgressRoute
  '/api/verbs/review': typeof ApiVerbsReviewRoute
  '/api/verbs/': typeof ApiVerbsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/health'
    | '/api/version'
    | '/api/auth/$'
    | '/api/auth/hasura-jwt'
    | '/api/verbs/$verbId'
    | '/api/verbs/add-to-queue'
    | '/api/verbs/practice'
    | '/api/verbs/practice-session'
    | '/api/verbs/progress'
    | '/api/verbs/review'
    | '/api/verbs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/health'
    | '/api/version'
    | '/api/auth/$'
    | '/api/auth/hasura-jwt'
    | '/api/verbs/$verbId'
    | '/api/verbs/add-to-queue'
    | '/api/verbs/practice'
    | '/api/verbs/practice-session'
    | '/api/verbs/progress'
    | '/api/verbs/review'
    | '/api/verbs'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/health'
    | '/api/version'
    | '/api/auth/$'
    | '/api/auth/hasura-jwt'
    | '/api/verbs/$verbId'
    | '/api/verbs/add-to-queue'
    | '/api/verbs/practice'
    | '/api/verbs/practice-session'
    | '/api/verbs/progress'
    | '/api/verbs/review'
    | '/api/verbs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthHasuraJwtRoute: typeof ApiAuthHasuraJwtRoute
  ApiVerbsVerbIdRoute: typeof ApiVerbsVerbIdRoute
  ApiVerbsAddToQueueRoute: typeof ApiVerbsAddToQueueRoute
  ApiVerbsPracticeRoute: typeof ApiVerbsPracticeRoute
  ApiVerbsPracticeSessionRoute: typeof ApiVerbsPracticeSessionRoute
  ApiVerbsProgressRoute: typeof ApiVerbsProgressRoute
  ApiVerbsReviewRoute: typeof ApiVerbsReviewRoute
  ApiVerbsIndexRoute: typeof ApiVerbsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/hasura-jwt': {
      id: '/api/auth/hasura-jwt'
      path: '/api/auth/hasura-jwt'
      fullPath: '/api/auth/hasura-jwt'
      preLoaderRoute: typeof ApiAuthHasuraJwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/': {
      id: '/api/verbs/'
      path: '/api/verbs'
      fullPath: '/api/verbs/'
      preLoaderRoute: typeof ApiVerbsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/$verbId': {
      id: '/api/verbs/$verbId'
      path: '/api/verbs/$verbId'
      fullPath: '/api/verbs/$verbId'
      preLoaderRoute: typeof ApiVerbsVerbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/add-to-queue': {
      id: '/api/verbs/add-to-queue'
      path: '/api/verbs/add-to-queue'
      fullPath: '/api/verbs/add-to-queue'
      preLoaderRoute: typeof ApiVerbsAddToQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/practice': {
      id: '/api/verbs/practice'
      path: '/api/verbs/practice'
      fullPath: '/api/verbs/practice'
      preLoaderRoute: typeof ApiVerbsPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/practice-session': {
      id: '/api/verbs/practice-session'
      path: '/api/verbs/practice-session'
      fullPath: '/api/verbs/practice-session'
      preLoaderRoute: typeof ApiVerbsPracticeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/progress': {
      id: '/api/verbs/progress'
      path: '/api/verbs/progress'
      fullPath: '/api/verbs/progress'
      preLoaderRoute: typeof ApiVerbsProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verbs/review': {
      id: '/api/verbs/review'
      path: '/api/verbs/review'
      fullPath: '/api/verbs/review'
      preLoaderRoute: typeof ApiVerbsReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthHasuraJwtRoute: ApiAuthHasuraJwtRoute,
  ApiVerbsVerbIdRoute: ApiVerbsVerbIdRoute,
  ApiVerbsAddToQueueRoute: ApiVerbsAddToQueueRoute,
  ApiVerbsPracticeRoute: ApiVerbsPracticeRoute,
  ApiVerbsPracticeSessionRoute: ApiVerbsPracticeSessionRoute,
  ApiVerbsProgressRoute: ApiVerbsProgressRoute,
  ApiVerbsReviewRoute: ApiVerbsReviewRoute,
  ApiVerbsIndexRoute: ApiVerbsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
